### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'Data/birds/example_captions.t7'

### ISSUE THREAD

**Issue by panovr** [brangerbriz/docker-StackGAN#3]
```
~/StackGAN# sh demo/birds_demo.sh 
demo/birds_demo.sh: 10: demo/birds_demo.sh: th: not found
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "demo/demo.py", line 175, in <module>
    t_file = torchfile.load(cap_path)
  File "/usr/local/lib/python2.7/dist-packages/torchfile.py", line 378, in load
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'Data/birds/example_captions.t7'
```
```
~/StackGAN# sh demo/flowers_demo.sh 
demo/flowers_demo.sh: 10: demo/flowers_demo.sh: th: not found
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "demo/demo.py", line 175, in <module>
    t_file = torchfile.load(cap_path)
  File "/usr/local/lib/python2.7/dist-packages/torchfile.py", line 378, in load
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'Data/flowers/example_captions.t7'
```

**Comment by brannondorsey** [comment]
It seems like Torch (`th`) hasn't been installed in the container. Did you run the `install_torch.sh` script?

**Comment by brannondorsey** [comment]
If so, try it again and type "yes" once the script prompts after torch is downloaded so that the torch bin/ is appended to your `.bashrc`. Also, see #1.

**Comment by panovr** [comment]
Run `source .bashrc` can solve this problem, maybe this can be added to readme? Now I can run `sh demo/birds_demo.sh`. May I ask where can I find the generated images?

**Comment by brannondorsey** [comment]
Great, glad it's working for you. I will add it to the readme. I'm AFK right now and can't remember the exact directory where you will find the generated images, but the StackGAN repo README shout tell you.

**Comment by panovr** [comment]
Find results in `Data/birds/example_captions`. Thanks for sharing this docker image!

**Comment by brannondorsey** [comment]
No problem, glad it is useful for you :)

**Comment by ast1997** [comment]
> install_torch.sh


Can you tell me how to install torch @brannondorsey
