### ISSUE TITLE
for non-GPU versions: cunn install errors

### ISSUE THREAD

**Issue by RJ722** [brangerbriz/docker-StackGAN#6]
I don't have a NVIDIA chip on my machine, so I cannot install `cunn`. Does this mean I cannot generate images ?
```
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cunn' not found:No LuaRocks module found for cunn
	no field package.preload['cunn']
	no file '/root/.luarocks/share/lua/5.1/cunn.lua'
	no file '/root/.luarocks/share/lua/5.1/cunn/init.lua'
	no file '/root/torch/install/share/lua/5.1/cunn.lua'
	no file '/root/torch/install/share/lua/5.1/cunn/init.lua'
	no file './cunn.lua'
	no file '/root/torch/install/share/luajit-2.1.0-beta1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/cunn.so'
	no file '/root/torch/install/lib/lua/5.1/cunn.so'
	no file '/root/torch/install/lib/cunn.so'
	no file './cunn.so'
	no file '/usr/local/lib/lua/5.1/cunn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	demo/get_embedding.lua:7: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
Traceback (most recent call last):
  File "demo/demo.py", line 175, in <module>
    t_file = torchfile.load(cap_path)
  File "/usr/local/lib/python2.7/dist-packages/torchfile.py", line 422, in load
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'Data/birds/example_captions.t7'
```
Also, torch is working `th` but still the `IOError` 😕 
Here's my `.bashrc`
```sh
root@29798aadddaa:~/StackGAN# cat ../.bashrc 
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
#    . /etc/bash_completion
#fi
# If the /root/StackGAN directory is empty, clone StackGAN into it
test "$(ls -A /root/StackGAN 2>/dev/null)" || git clone https://github.com/hanzhanggit/StackGAN.git


. /root/torch/install/bin/torch-activate
```

Thank you for providing a docker image! 😄

**Comment by akshay-patade** [comment]
I have the same issue . Can somebody please help

**Comment by ghost** [comment]
> I have the same issue . Can somebody please help

+1
